name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      REGISTRY: ghcr.io
      IMAGE: semantic-release
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Docker Build
        run: docker build . --tag localbuild/image:latest
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/github
      - name: Docker Login
        run: echo ${GH_TOKEN} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Docker Tag Release
        run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:v${{ steps.semantic.outputs.new_release_version }}
      - name: Docker Push Release
        run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:v${{ steps.semantic.outputs.new_release_version }}
      - name: Docker Tag Latest
        run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest
      - name: Docker Push Latest
        run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest